/* --------------------------------------------------------------------------------
 * Autores:     Daniel de Souza Baulé
 *              Mirian de França Santos Pereira
 * Disciplina:  INE5417 - Engenharia de Software
 * Projeto:     Edito de Texto
-------------------------------------------------------------------------------- */

package Visao;

import Dados.Documento;
import Dados.Formatacao;
import Dados.INEdit;
import Dados.MapeadorDocumento;
import Dados.MapeadorFormatacao;
import Dados.MapeadorUsuario;
import Dados.Usuario;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class EditorDeTexto extends javax.swing.JFrame {

    Usuario usuario;
    Documento documento;
    Formatacao formatacao;
    
    INEdit inedit;

    /**
     * Creates new form Tela_Principal
     */
    public EditorDeTexto() {
        inedit = new INEdit();
        
        initComponents();
        
        this.setTitle("INEdit");        // Altera o título
        AreaDoTexto.setVisible(false);   // Inicia a área de texto sem edição habilitada
        BotaoSalvar.setEnabled(false);  // Inicia o botão salvar desabilitado (Até abertura ou criação de um arquivo)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JanelaEscolheArquivo = new javax.swing.JFileChooser();
        JanelaEscolhePasta = new javax.swing.JFileChooser();
        JanelaEscolheUsuario = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDoTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoArquivo = new javax.swing.JMenu();
        BotaoNovo = new javax.swing.JMenuItem();
        BotaoAbrir = new javax.swing.JMenuItem();
        BotaoSalvar = new javax.swing.JMenuItem();
        botaoINEdit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        botaoAjuda = new javax.swing.JMenuItem();

        JanelaEscolheArquivo.setCurrentDirectory(new java.io.File("C:\\"));
            JanelaEscolheArquivo.setDialogTitle("Seleção de Arquivo");
            JanelaEscolheArquivo.setFileFilter(new FiltroArquivo());
            JanelaEscolheArquivo.setToolTipText("Selecione o arquivo .txt a ser aberto.");

            JanelaEscolhePasta.setDialogTitle("Seleção de Pasta");
            JanelaEscolhePasta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            JanelaEscolhePasta.setToolTipText("Selecione a pasta onde sera criado o novo arquivo.");

            JanelaEscolheUsuario.setPreferredSize(new java.awt.Dimension(500, 500));

            jTextField1.setText("Nome");
            jTextField1.setPreferredSize(new java.awt.Dimension(500, 50));
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jButton1.setText("Adicionar Usuário");

            jList2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane3.setViewportView(jList2);

            jButton2.setText("Selecionar Usuário");

            javax.swing.GroupLayout JanelaEscolheUsuarioLayout = new javax.swing.GroupLayout(JanelaEscolheUsuario.getContentPane());
            JanelaEscolheUsuario.getContentPane().setLayout(JanelaEscolheUsuarioLayout);
            JanelaEscolheUsuarioLayout.setHorizontalGroup(
                JanelaEscolheUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JanelaEscolheUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JanelaEscolheUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JanelaEscolheUsuarioLayout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            JanelaEscolheUsuarioLayout.setVerticalGroup(
                JanelaEscolheUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JanelaEscolheUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JanelaEscolheUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            AreaDoTexto.setColumns(20);
            AreaDoTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            AreaDoTexto.setLineWrap(true);
            AreaDoTexto.setRows(5);
            AreaDoTexto.setTabSize(4);
            jScrollPane1.setViewportView(AreaDoTexto);

            botaoArquivo.setText("Arquivo");

            BotaoNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
            BotaoNovo.setText("Novo");
            BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotaoNovoActionPerformed(evt);
                }
            });
            botaoArquivo.add(BotaoNovo);

            BotaoAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
            BotaoAbrir.setText("Abrir");
            BotaoAbrir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotaoAbrirActionPerformed(evt);
                }
            });
            botaoArquivo.add(BotaoAbrir);

            BotaoSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
            BotaoSalvar.setText("Salvar");
            BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotaoSalvarActionPerformed(evt);
                }
            });
            botaoArquivo.add(BotaoSalvar);

            jMenuBar1.add(botaoArquivo);

            botaoINEdit.setText("INEdit");

            jMenuItem1.setText("Sobre");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            botaoINEdit.add(jMenuItem1);

            botaoAjuda.setText("Ajuda");
            botaoAjuda.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botaoAjudaActionPerformed(evt);
                }
            });
            botaoINEdit.add(botaoAjuda);

            jMenuBar1.add(botaoINEdit);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    //! Botão para criação de um novo arquivo
    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed

        String[] usuarios = inedit.retornaUsuarios();
        
        criaNovoUsuario();
        
        if(usuarios != null) {
            Object[] options = usuarios;
            Object selecao = JOptionPane.showInputDialog(this, "Choose", "Menu", JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
        }

        int returnVal = JanelaEscolhePasta.showOpenDialog(this);    // Obtem a pasta para criação do novo arquivo através de um dialogo do sistema
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String NomeArquivo = JOptionPane.showInputDialog(this, "Nome do arquivo:", "Novo Arquivo", JOptionPane.PLAIN_MESSAGE);  // Obtem o nome para o novo arquivo
            // documento = new Documento(JanelaEscolhePasta.getSelectedFile(), NomeArquivo);   // Criação do novo documento
            AreaDoTexto.setText(documento.getTexto());   // Leitura do arquivo (Provavelmente vazio)
            AreaDoTexto.setVisible(true);    // Habilitação da edição de texto
            BotaoSalvar.setEnabled(true);   // Habilitação do botão salvar
        } else {
            System.out.println("Acesso cancelado pelo usuário!");
        }
    }//GEN-LAST:event_BotaoNovoActionPerformed
    
    //! Botão para abertura de um arquivo
    private void BotaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirActionPerformed
        int returnVal = JanelaEscolheArquivo.showOpenDialog(this);    // Obtem o caminho para o arquivo a ser aberto através de um diálogo do sistema
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // documento = new Documento(JanelaEscolheArquivo.getSelectedFile());  // Lê o documento selecionado
            AreaDoTexto.setText(documento.getTexto());   // Leitura do texto
            AreaDoTexto.setVisible(true);    // Habilitação da edição de texto
            BotaoSalvar.setEnabled(true);   // Habilitação do botão salvar
        } else {
            System.out.println("Acesso cancelado pelo usuário!");
        }
    }//GEN-LAST:event_BotaoAbrirActionPerformed
    
    //! Botão para salvar o arquivo
    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        documento.setTexto(AreaDoTexto.getText());   // Alteração do texto do documento
        // documento.salvarArquivo();  // Salvar o documento
        JOptionPane.showMessageDialog(this, "Arquivo Salvo");   // Mostrar um diálogo para confirmação do salvamento do arquivo
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaSobre telaSobre = new TelaSobre();
        telaSobre.setLocationRelativeTo(this);
        telaSobre.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaSobre.pack();
        telaSobre.setVisible(true);    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaActionPerformed
        TelaAjuda telaAjuda = new TelaAjuda();
        telaAjuda.setLocationRelativeTo(this);
        telaAjuda.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_botaoAjudaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorDeTexto().setVisible(true);
            }
        });
    }
    
    private Usuario criaNovoUsuario() {
        Usuario usuarioCriado = null;
        while(usuarioCriado == null) {
            String nomeUsuario = JOptionPane.showInputDialog(this, "Nome do Usuario:", "Novo Usuario", JOptionPane.PLAIN_MESSAGE);  // Obtem o nome para o novo Usuario;
            if(inedit.retornaUsuario(nomeUsuario) == null) {
                inedit.cadastraUsuario(new Usuario(nomeUsuario));
                usuarioCriado = inedit.retornaUsuario(nomeUsuario);
            }
        }
        return usuarioCriado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDoTexto;
    private javax.swing.JMenuItem BotaoAbrir;
    private javax.swing.JMenuItem BotaoNovo;
    private javax.swing.JMenuItem BotaoSalvar;
    private javax.swing.JFileChooser JanelaEscolheArquivo;
    private javax.swing.JFileChooser JanelaEscolhePasta;
    private javax.swing.JFrame JanelaEscolheUsuario;
    private javax.swing.JMenuItem botaoAjuda;
    private javax.swing.JMenu botaoArquivo;
    private javax.swing.JMenu botaoINEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

//! Filtro para arquivos .txt
class FiltroArquivo extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
    }

    @Override
    public String getDescription() {
        return "Text documents (*.txt)";
    }
}
