/* --------------------------------------------------------------------------------
 * Autores:     Daniel de Souza Baulé
 *              Mirian de França Santos Pereira
 * Disciplina:  INE5417 - Engenharia de Software
 * Projeto:     Edito de Texto
-------------------------------------------------------------------------------- */

package Visao;

import Dados.Documento;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class EditorDeTexto extends javax.swing.JFrame {

    Documento documento;

    /**
     * Creates new form Tela_Principal
     */
    public EditorDeTexto() {
        initComponents();
        this.setTitle("INEdit");        // Altera o título
        AreaDoTexto.setVisible(false);   // Inicia a área de texto sem edição habilitada
        BotaoSalvar.setEnabled(false);  // Inicia o botão salvar desabilitado (Até abertura ou criação de um arquivo)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JanelaEscolheArquivo = new javax.swing.JFileChooser();
        JanelaEscolhePasta = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDoTexto = new javax.swing.JTextArea();
        barraDoMenu = new javax.swing.JMenuBar();
        botaoArquivo = new javax.swing.JMenu();
        BotaoNovo = new javax.swing.JMenuItem();
        BotaoAbrir = new javax.swing.JMenuItem();
        BotaoSalvar = new javax.swing.JMenuItem();
        botaoINEdit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        botaoAjuda = new javax.swing.JMenuItem();

        JanelaEscolheArquivo.setCurrentDirectory(new java.io.File("/home/100000000473471/C:"));
        JanelaEscolheArquivo.setDialogTitle("Seleção de Arquivo");
        JanelaEscolheArquivo.setFileFilter(new FiltroArquivo());
        JanelaEscolheArquivo.setToolTipText("Selecione o arquivo .txt a ser aberto.");

        JanelaEscolhePasta.setDialogTitle("Seleção de Pasta");
        JanelaEscolhePasta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        JanelaEscolhePasta.setToolTipText("Selecione a pasta onde sera criado o novo arquivo.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaDoTexto.setColumns(20);
        AreaDoTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AreaDoTexto.setLineWrap(true);
        AreaDoTexto.setRows(5);
        AreaDoTexto.setTabSize(4);
        jScrollPane1.setViewportView(AreaDoTexto);

        botaoArquivo.setText("Arquivo");

        BotaoNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        BotaoNovo.setText("Novo");
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });
        botaoArquivo.add(BotaoNovo);

        BotaoAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        BotaoAbrir.setText("Abrir");
        BotaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirActionPerformed(evt);
            }
        });
        botaoArquivo.add(BotaoAbrir);

        BotaoSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        botaoArquivo.add(BotaoSalvar);

        barraDoMenu.add(botaoArquivo);

        botaoINEdit.setText("INEdit");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        botaoINEdit.add(jMenuItem1);

        botaoAjuda.setText("Ajuda");
        botaoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaActionPerformed(evt);
            }
        });
        botaoINEdit.add(botaoAjuda);

        barraDoMenu.add(botaoINEdit);

        setJMenuBar(barraDoMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //! Botão para criação de um novo arquivo
    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        int returnVal = JanelaEscolhePasta.showOpenDialog(this);    // Obtem a pasta para criação do novo arquivo através de um dialogo do sistema
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String NomeArquivo = JOptionPane.showInputDialog(this, "Nome do arquivo:", "Novo Arquivo", JOptionPane.PLAIN_MESSAGE);  // Obtem o nome para o novo arquivo
            // documento = new Documento(JanelaEscolhePasta.getSelectedFile(), NomeArquivo);   // Criação do novo documento
            AreaDoTexto.setText(documento.getTexto());   // Leitura do arquivo (Provavelmente vazio)
            AreaDoTexto.setVisible(true);    // Habilitação da edição de texto
            BotaoSalvar.setEnabled(true);   // Habilitação do botão salvar
        } else {
            System.out.println("Acesso cancelado pelo usuário!");
        }
    }//GEN-LAST:event_BotaoNovoActionPerformed
    
    //! Botão para abertura de um arquivo
    private void BotaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirActionPerformed
        int returnVal = JanelaEscolheArquivo.showOpenDialog(this);    // Obtem o caminho para o arquivo a ser aberto através de um diálogo do sistema
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // documento = new Documento(JanelaEscolheArquivo.getSelectedFile());  // Lê o documento selecionado
            AreaDoTexto.setText(documento.getTexto());   // Leitura do texto
            AreaDoTexto.setVisible(true);    // Habilitação da edição de texto
            BotaoSalvar.setEnabled(true);   // Habilitação do botão salvar
        } else {
            System.out.println("Acesso cancelado pelo usuário!");
        }
    }//GEN-LAST:event_BotaoAbrirActionPerformed
    
    //! Botão para salvar o arquivo
    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        documento.setTexto(AreaDoTexto.getText());   // Alteração do texto do documento
        // documento.salvarArquivo();  // Salvar o documento
        JOptionPane.showMessageDialog(this, "Arquivo Salvo");   // Mostrar um diálogo para confirmação do salvamento do arquivo
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaSobre telaSobre = new TelaSobre();
        telaSobre.setLocationRelativeTo(this);
        telaSobre.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaSobre.pack();
        telaSobre.setVisible(true);    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaActionPerformed
        TelaAjuda telaAjuda = new TelaAjuda();
        telaAjuda.setLocationRelativeTo(this);
        telaAjuda.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_botaoAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorDeTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDoTexto;
    private javax.swing.JMenuItem BotaoAbrir;
    private javax.swing.JMenuItem BotaoNovo;
    private javax.swing.JMenuItem BotaoSalvar;
    private javax.swing.JFileChooser JanelaEscolheArquivo;
    private javax.swing.JFileChooser JanelaEscolhePasta;
    private javax.swing.JMenuBar barraDoMenu;
    private javax.swing.JMenuItem botaoAjuda;
    private javax.swing.JMenu botaoArquivo;
    private javax.swing.JMenu botaoINEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

//! Filtro para arquivos .txt
class FiltroArquivo extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
    }

    @Override
    public String getDescription() {
        return "Text documents (*.txt)";
    }
}